// Generated by Xata Codegen 0.18.0. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "log",
    columns: [
      { name: "description", type: "text" },
      {
        name: "discordUserId",
        type: "string",
        notNull: true,
        defaultValue: "",
      },
      {
        name: "createdTimestamp",
        type: "datetime",
        notNull: true,
        defaultValue: "2021-04-01T18:46:52.292Z",
      },
      {
        name: "logDate",
        type: "datetime",
        notNull: true,
        defaultValue: "2021-01-01T18:47:57.127Z",
      },
      { name: "editedTimestamp", type: "datetime" },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://Queen-Raae-Workspace-edpk3k.eu-west-1.xata.sh/db/yoga-pirates",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
